import { auth } from './firebase.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-auth.js';
import { getUserProfile, watchBoard, watchState, watchTeam, watchSheet, reconcileDraftState } from './service.js';
import { loadRankings } from './rankings.js';
import { getNextOpenSlot } from './model.js';
import { AutoPickConductor } from './autopick.js';
const $=id=>document.getElementById(id); let board={teams:[],picks:{}},state={},teams=new Map(),sheets=new Map(),conductor=null;
$('loginBtn').onclick=()=>signInWithEmailAndPassword(auth,$('email').value,$('password').value).catch(e=>$('err').textContent=e.message);$('logoutBtn').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){conductor?.stop();$('loginCard').hidden=false;$('app').hidden=true;return;}const p=await getUserProfile(user.uid);if(p?.role!=='admin'){ $('err').textContent='Dieses Konto ist nicht als admin hinterlegt.';await signOut(auth);return;}$('loginCard').hidden=true;$('app').hidden=false;await loadRankings();watchBoard(async b=>{board=b;await reconcileDraftState(b).catch(console.error);bindTeams();render()});watchState(s=>{state=s;render()});conductor=new AutoPickConductor({ownerId:user.uid,getBoard:()=>board,getState:()=>state,getTeam:id=>teams.get(id),getSheet:id=>sheets.get(id),onCountdown:c=>{$('auto').textContent=c?`Autopick #${c.overall} in ${Math.ceil(c.ms/1000)}s`:'Kein Autopick-Countdown.'}});const ok=await conductor.start();$('lease').textContent=ok?'🟢 ACTIVE CONDUCTOR':'🟡 PASSIVE (anderer Tab aktiv)';});
let bound=new Set();function bindTeams(){for(const id of board.teams||[]){if(!id||bound.has(id))continue;bound.add(id);watchTeam(id,t=>{teams.set(id,t||{});renderTeams()});watchSheet(id,s=>sheets.set(id,s||{}))}}function render(){const n=getNextOpenSlot(board.picks||{});$('current').textContent=n?`${board.teams?.[n.position-1]||'—'} · Runde ${n.round} · Pick #${n.overall}`:'Draft beendet';}function renderTeams(){$('teams').innerHTML=(board.teams||[]).filter(Boolean).map(id=>`<div style="display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #26303d"><span>${id}</span><b>${teams.get(id)?.attendance||'present'}</b></div>`).join('')}
